### ISSUE TITLE
Transaction validation and dynamic participants

### ISSUE THREAD

**Issue by Champii** [mosaicnetworks/babble#31]
Hi !

I can't find a way to validate a transaction when received by gossip in order to exclude the invalid ones by consensus, is it assumed that all participating nodes agree de facto that all transaction content is valid ?
I might miss something here :)

Also, you state in your doc that we can't change the peers set at runtime but that it's an `implemention prioritization`. How hard will it be to add this feature to the network ? Is it planned ? Would you need some hands ? :)

Cheers !

**Comment by arrivets** [comment]
Hi!

You are correct; there is no way of validating transactions yet and it is possible for invalid transactions to be added to the hashgraph and go through consensus. It is up to the application layer to discard invalid transactions. Obviously this is not great because one could spam the network with invalid transactions. We would need a way to check an Event's transactions before adding to the Hashgraph. But the check would be limited because, at that stage, the order of transactions is not known yet.

We definitely plan to enable changing the list of participants at runtime.. we call that 'dynamic participants'. It is very challenging actually. It is on our roadmap and we expect to have it by the end of the year.. help is obviously welcome!!

The idea is that when someone wants to join, they submit a JoinRequest to one of the nodes, and this request goes through consensus as a special type of transaction. The application layer decides whether or not the request is accepted; if so, the participants list is updated.. devil is in the details of course

Help is more than welcome! :)

Best

**Comment by Champii** [comment]
It's great to ear that you are actively running this amazing project :)

Even if the transaction validation would be effectively limited at the point they are primarily received by the App, it would be nice anyway to run some sort of pre-check, likely to be rechecked on whole block commit for order validity maybe ?

About that, what happen when an app return an error to Babble on CommitBlock RPC event ? Does that invalidate the block ?

The simplest way to pre-validate transactions IMHO would be to add a CheckTx() RPC endpoint on the BabbleProxy (app side) that would allow or not the transaction to be added in the hashgraph event. This can be achieve by calling that endpoint from inside of `node.Sync()` 
I'm running some tests on that in my fork.

Btw, how nice would it be to have a real InAppFullProxy to avoid making an RPC connection when using Babble directly from the source ? That would also allow to limit the opened socket when running a lot of local nodes. I find the existing InAppProxy somewhat great for tests but not for this purpose.

I'm really looking into a join procedure like the one you described, effectively this is touchy as it adds a whole new layer of possible failures and security problems. 
I might also give it a try as a POC in my fork to determine the problematic of such a complex feature

I will get back to you shortly about that !

Regards

EDIT: `node.Sync()` instead of `core.InsertEvent()` because we do not have access to the proxy there

**Comment by arrivets** [comment]
Thanks!

Good idea. Maybe we can have two levels of checking: 1 at the ```node.Sync()``` stage as you mentioned (where we filter garbage transactions without even considering their order), and a later one at the moment of committing the block where we remove all the invalid transactions from the block (the ones that failed because of ordering). This way, invalid transactions would be persisted in the Hashgaph but not in the Blockchain. That would be acceptable because the hashgraph is just a support for the consensus algorithm whereas the blockchain serves for accountability and persisting the history of transactions.

Even if the Commit() fails, the block is still saved locally. It just keeps an empty statehash. Not sure if we should implement retries here..

About the inmemory proxy, I completely agree with you. We want to be able to instantiate and use a node from golang directly. Should be quite straight forward. As a matter of fact, if you look in the mobile package, you will see that we created a wrapper around the `node` object. This object is used to create Java bindings such that a Babble node can be instantiated inmemory from Java code. So we know how to do it :)

Looking forward to your pull request or updates!

**Comment by Champii** [comment]
Hi !

I worked a big part of the night on the process of adding a Peer, and this morning I can connect a third peer to an existing cluster of two nodes, it starts syncing but when it comes to adding a fourth node, the first two get `io timeout` from that third node. 

I tried to use an external JOIN process that runs through the network, and I have to add new Peers with `node.AddPeer(pubkey []byte, addr string) error `. 
In coordination with a endpoint `OnPeerConnect(*Peer) bool` in the BabbleProxyServer to accept or deny a new connection, we can use an external process to manage the list of peers without relying on an internal consensus mecanism. We may also need to check gossips that would include unknown or denied peers reference, remove them and disconnect the node that carry them (not a easy process tho).

In that process, I asked myself about the real utility to have a fixed set of integer ID for each peer, as we are already identifying them with their public keys. It is a great concern as adding a new peer might change the attribution of the ids. 
So I tried to remove that notion from Babble to only keep track of the pubkey as a mean of identification (actually I use the whole key as ID but I need to use a SHA256 hash instead). (EDIT: This is kind of cocky as I needed to use `map` instead of slices everywhere in the code, which may impact the performances) . I managed to change the code and the tests, but still some are not passing (that may explain my first `io timeout` error btw)
I still need thoses tests to pass in the hashgraph:
- TestInsertEventsWithBlockSignatures
- TestReset
- TestGetFrame
- TestResetFromFrame

Well, even if i'm probably doing shit right now in the code and if I may have broke some things, I'm having fun ^^. Also i'm really open to critics, and I greatly need your opinion on my first thoughts !

Have a great day. !

**Comment by arrivets** [comment]
Wow! I wasnt expecting that.

The fixed set of integers for peers ID will indeed break with dynamic participants. It was introduced only to make the gossip messages smaller.. a classic example of trying to optimize things too early. So the easiest thing to do is to use ```Event``` instead of ```WireEvent``` in all the networking... and forget about ```WireEvent``` for now. That will actually remove a lot of the complexity from the current code. It removes the need to convert to and from ```WireEvent```.

Regarding the JOIN process, that sounds amazing. Congratulations. I am not sure what you mean by "use an external process to manage the list of peers without relying on an internal consensus mecanism". Do you mean that the peers do not need to have the same list of participants at all times? I had never thought of that but it sounds like there is something interesting there... because nodes will see messages from peers they are not necessarily aware of anyway, as the hashraph contains the entire history of gossip, and includes all nodes..   Super interesting. I look forward to hearing more about your idea.

Cheers!

**Comment by Champii** [comment]
I wanted to do to much at the same time, I can't have the tests to pass and I have no clue why..
I'll have to start over more carefully, I'll keep you informed :)

**Comment by arrivets** [comment]
ahh that also means we need more tests to make it easier to debug.
Let me know if I can help.

**Comment by arrivets** [comment]
Hi @Champii !
Have you made any progress with this?

**Comment by Champii** [comment]
Hello @arrivets no, I just come back from holidays and i've not made much progress before that.
But I will soon reopen that project, i will certainly have plenty of questions :)

**Comment by arrivets** [comment]
Nice. 
Ping me at martin@babble.io if you would like to discuss this in a separate channel.
We have setup a bounty program for code contributions and we are also in the process of
hiring developers. 
https://medium.com/@monet.network

**Comment by hayyudin** [comment]
It's very serious discussion here.
