### ISSUE TITLE
What is the licence for this?

### ISSUE THREAD

**Issue by harishpillay** [mosaicnetworks/babble#4]
I am not seeing what license babble is being placed under. Is it GPLv3 (I prefer that)?

**Comment by arrivets** [comment]
Its the "do whatever you want" license :)
Just be careful because the algorithm is patented in the US and they have some applications pending in Europe. We do not take any responsibility for legal issues that might arise from using the Hashgraph algorithm without authorization from the patent holders (Swirlds).

**Comment by harishpillay** [comment]
Thanks for the reply. Noted about the software patents they have. Software patents are not applicable in the jurisdiction I am in (Singapore). Instead of focusing on the tech, it is a pity that we are discussing software patents.

**Comment by arrivets** [comment]
Glad to help. Well I hope you find Babble useful for your projects!

**Comment by stevenroose** [comment]
If [there is no license](https://softwareengineering.stackexchange.com/questions/276144/using-unlicensed-code), it keeps _all rights reserved_ to the copyright holders, meaning that modifying and redistribution are copyright infringements in most legislations. 

If you want the software to be freely usable by anyone, add an MIT license. Note, however, that since you have two external contributors, you have to ask their permission in order to apply a license to the current project, or exclude their contributions.
