### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by qiangxue** [mosaicnetworks/babble#9]
Nice work! What is the license for this project?

**Comment by arrivets** [comment]
Thanks. There is no license. You are free to do whatever you want with the code.
Just be careful because the algorithm is patented in the US.

**Comment by qiangxue** [comment]
Wonderful! Thanks!

**Comment by stevenroose** [comment]
If [there is no license](https://softwareengineering.stackexchange.com/questions/276144/using-unlicensed-code), it keeps _all rights reserved_ to the copyright holders, meaning that modifying and redistribution are copyright infringements in most legislations. 

If you want the software to be freely usable by anyone, add an MIT license. Note, however, that since you have two external contributors, you have to ask their permission in order to apply a license to the current project, or exclude their contributions.

**Comment by hce** [comment]
Could you please specify a license as was suggested, or declare the project as "public domain"? That'd be very helpful :-)

**Comment by Serkan-devel** [comment]
But with the  recent acquisition by Microsoft, they can claim everything published on Github without a license here as their own

**Comment by arrivets** [comment]
Thanks, 
Sorry I forgot about this issue.
Added MIT License
